opencost:
  exporter:
    defaultClusterId: "gpu-idle-predictor-local"
  prometheus:
    internal:
      enabled: true
      serviceName: prometheus-kube-prometheus-prometheus
      namespaceName: monitoring
      port: 9090
    external:
      enabled: false
  prices:
    CPU: 0.0
    RAM: 0.0
    GPU: 0.60
